# Generated by Django 5.2.2 on 2025-06-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='email',
            field=models.EmailField(default='prof@example.com', max_length=254),
        ),
    ]
