# Generated by Django 5.2.2 on 2025-06-06 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_enseignant_description_enseignant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.enseignant'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ressource'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='titre',
            field=models.CharField(max_length=255),
        ),
    ]
