# Generated by Django 5.2.2 on 2025-06-06 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_examen_enseignant_alter_examen_ressource_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ressource',
            old_name='descriptif',
            new_name='description',
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='code',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='coefficient',
        ),
        migrations.RemoveField(
            model_name='ue',
            name='code',
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='prenom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='groupe',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='examen',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.enseignant'),
        ),
        migrations.AlterField(
            model_name='note',
            name='appreciation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.etudiant'),
        ),
        migrations.AlterField(
            model_name='note',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.examen'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ue'),
        ),
        migrations.AlterField(
            model_name='ue',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
